[package]
name = "lighthouse"
version = "0.1.0"
authors = ["Damon Myers <damon.shane.myers@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
