# The address to listen for connections on. Defaults to 127.0.0.1
bind_address = "127.0.0.1"
# The port to listen for connections on. Defaults to 8000
port = 8000
# The DNS name for the server. Defaults to "localhost"
domain = "localhost"
